### ISSUE TITLE
using imported functions only works with one argument

### ISSUE THREAD

**Issue by danvegeto** [danvegeto/pipelinescript#29]
This doesn't translate:

```
function f = !"script.py"
print f()
print f("arg1", "arg2", "arg3")
```

**Comment by lolemacs** [comment]
The syntax we're using so far is:
print f("arg1"  "arg2"  "arg3")

Just like in functional programming languages. I'll add the commas when I add the semi-colons in a few, but let's set this as low priority since theoretically it does work.
