### ISSUE TITLE
implement Graph class

### ISSUE THREAD

**Issue by danvegeto** [danvegeto/pipelinescript#3]

**Comment by burakfirik** [comment]
added Graph class

**Comment by danvegeto** [comment]
- inherit from Table
- indexes only for each node
- weights for each edge

notes:

toCSV() (default of toString)
toCSV(String delim)
toCSV(String delim, String quote)

table.toCSV("\t")

String[][] -> CSV
String[][] -> TSV
String[][] -> XML
String[][] -> JSON

**Comment by burakfirik** [comment]
completed the methods and requirements
